"""modified flight and booking models

Revision ID: 6c3e8a414b23
Revises: 8a6b04cf87dd
Create Date: 2023-10-09 00:03:24.005183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3e8a414b23'
down_revision = '8a6b04cf87dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bookings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('seat_number')
        batch_op.drop_column('price')

    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flights', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('seat_number', sa.VARCHAR(length=10), nullable=False))

    op.create_table('_alembic_tmp_bookings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('flight_id', sa.INTEGER(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('order_status', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], name='fk_bookings_flight_id_flights'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_bookings_user_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    # ### end Alembic commands ###
